// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.cart = [];
  $scope.addBookToCart = function(book) {
    var bookIndex;
    bookIndex = $scope.cart.indexOf(book);
    if (bookIndex === -1) {
      book.quantity = 1;
      $scope.cart.push(book);
    } else {
      $scope.cart[bookIndex].quantity += 1;
    }
  };
  $scope.emptyCart = function() {
    var book, _i, _len, _ref;
    _ref = $scope.cart;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      book = _ref[_i];
      $scope.cart.pop();
    }
  };
  $scope.bookSort = 'title';
  $scope.cartTotal = function() {
    var book, sum, _i, _len, _ref;
    sum = 0;
    _ref = $scope.cart;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      book = _ref[_i];
      sum += book.price * book.quantity;
    }
    return sum;
  };
};
